---
- name: noaa environment variables
  template:
    src: noaa-v2.conf.j2
    dest: ~daenks/.noaa-v2.conf
    owner: daenks
    group: daenks
    mode: 0644

- name: predict directory
  file:
    path: ~daenks/.predict
    state: directory
    owner: daenks
    group: daenks
    mode: 0755

- name: predict config file
  template:
    src: predict.qth.j2
    dest: ~daenks/.predict/predict.qth
    owner: daenks
    group: daenks
    mode: 0644

- name: wxtoimg config file
  template:
    src: wxtoimgrc.j2
    dest: ~daenks/.wxtoimgrc
    owner: daenks
    group: daenks
    mode: 0644

- name: wxtoimg license terms acceptance file
  copy:
    src: wxtoimglic
    dest: ~daenks/.wxtoimglic
    owner: daenks
    group: daenks
    mode: 0644

- name: log directory for raspberry-noaa-v2 logs
  become: yes
  file:
    path: /var/log/raspberry-noaa-v2
    state: directory
    owner: daenks
    group: daenks
    mode: 0755

- name: logrotate settings for raspberry-noaa-v2 logs
  become: yes
  copy:
    src: logrotate-settings
    dest: /etc/logrotate.d/raspberry-noaa-v2
    owner: root
    group: root
    mode: 0644

- name: gnuradio home directory
  file:
    path: ~daenks/.gnuradio
    state: directory
    owner: daenks
    group: daenks
    mode: 0755

- name: gnuradio prefs directory
  file:
    path: ~daenks/.gnuradio/prefs
    state: directory
    owner: daenks
    group: daenks
    mode: 0755

- name: gnuradio prefs file
  copy:
    src: vmcircbuf_default_factory
    dest: ~daenks/.gnuradio/prefs/vmcircbuf_default_factory
    owner: daenks
    group: daenks
    mode: 0644

- name: disable wifi power mgmt script
  become: yes
  copy:
    src: disable-wifi-powermgmt.sh
    dest: /usr/local/sbin/disable-wifi-powermgmt.sh
    owner: root
    group: root
    mode: 0755
  when: disable_wifi_power_mgmt | bool
  register: wifi_powermgmt_script

- name: disable wifi power mgmt service definition
  become: yes
  copy:
    src: disable-wifi-powermgmt.service
    dest: /lib/systemd/system/disable-wifi-powermgmt.service
    owner: root
    group: root
    mode: 0644
  when: disable_wifi_power_mgmt | bool
  register: wifi_powermgmt_service

- name: enable systemd wifi power management disable service
  become: yes
  systemd:
    daemon_reload: yes
    name: disable-wifi-powermgmt.service
    enabled: yes
  when: (wifi_powermgmt_script.changed or wifi_powermgmt_service.changed) and (disable_wifi_power_mgmt|bool)

- name: annotation directory
  file:
    path: ~daenks/config/annotation
    state: directory
    owner: daenks
    group: daenks
    mode: 0755

- name: annotation file (sample for modification)
  copy:
    src: annotation.html.j2_file
    dest: ~daenks/raspberry-noaa-v2/config/annotation/annotation.html.j2
    force: no
    owner: daenks
    group: daenks
    mode: 0600

- name: annotation file image (sample for modification)
  copy:
    src: raspberry-noaa-v2-logo.png
    dest: ~daenks/raspberry-noaa-v2/config/annotation/raspberry-noaa-v2-logo.png
    force: no
    owner: daenks
    group: daenks
    mode: 0600
...
