---
- name: install tweepy if twitter push is enabled
  become: yes
  pip:
    name: tweepy
    executable: daenksp3
    state: present
  when: enable_twitter_push | bool

- name: drop template twitter tweepy config file
  copy:
    src: tweepy.conf
    dest: /home/daenks/.tweepy.conf
    force: no
    owner: daenks
    group: daenks
    mode: 0600
  when: enable_twitter_push | bool
...
